@endpoingPhoenix = Phoenix
@endpoingFlagStaff = FlagStaff

### Base GET Request 1 Missing Endpoint
GET {{localHostName}}
Content-Type: application/json


### Base POST Request 1 Missing Endpoint
POST {{localHostName}}
Content-Type: application/json

#  EXC request Body
# <request>
#     <name>sample</name>
#     <time>Wed, 21 Oct 2015 18:27:50 GMT</time>
# </request>

### Phoenix Get Request 1
GET {{localHostName}}/{{endpoingPhoenix}}
Content-Type: application/json

### Flagstaff Get Request 1
GET {{localHostName}}/{{endpoingFlagStaff}}
Content-Type: application/json

